### ISSUE TITLE
Support caching for streamed responses

### ISSUE THREAD

**Issue by corbt** [OpenPipe/openpipe#159]
Right now our observability client libraries support both streaming responses and cached responses, but not both. If you attempt to stream a response and also enable checking the cache with the `openpipe: { cache: true }` option, the cache will be ignored and it will fall back to requesting the response from the provider directly (the streamed call will still be logged in your request logs).

Querying the cache for streamed values is easy, it's just a little bit tricky to then translate that into the format that a consumer expects.

**Comment by arcticfly** [comment]
Closed because we're deprioritizing caching.
