### ISSUE TITLE
Is it possible to run a chat conversation and run tests for each model answer?

### ISSUE THREAD

**Issue by ayrtondenner** [OpenPipe/openpipe#178]
I want to run a chat conversation with an LLM model and have some tests for the answer I'm going to get from each message.
Let's say that I have the following list of messages:

```
    {
      role: "user",
      content: "What is Facebook?",
    },
    {
      role: "user",
      content: "Who founded it?",
    },
    {
      role: "user",
      content: "When it was found?",
    }
```

As you can see, I want to send a message to a chat LLM, evaluate the answer, and then send another message where its context depends on the previous interaction. From the available demos, it looked like OpenPipe only works with a single answer per run.

**Comment by arcticfly** [comment]
Yes that's right. We don't currently provide a way to converse with an LLM. You can define multiple messages in the prompt editor, but there's no dynamic way to update scenario variables to contain new messages. You'd have to do that ahead of time.

Would this work for what you want to do? https://chat.lmsys.org/
