### ISSUE TITLE
Is it possible to evaluate using models from Azure OpenAI Service?

### ISSUE THREAD

**Issue by ayrtondenner** [OpenPipe/openpipe#194]
I have a model currently available via Azure OpenAI, is it possible to run a prompt through it passing AZURE_OPENAI_API_KEY and the Azure URL instead of using the models in "openai/ChatCompletion" for instance?

**Comment by corbt** [comment]
Unfortunately we don't support Azure-hosted models just yet, sorry!

**Comment by rbruels** [comment]
+1 on this! — Azure's OpenAI performance is pretty stellar compared to OpenAI itself, so a number of us are playing in that environment now

fwiw configuring the `openai` library to use the Azure models is pretty straightforward these days. 

TS: https://github.com/openai/openai-node/blob/v4/examples/azure.ts
Python: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints

**Comment by Pbmangan** [comment]
Can confirm if you use your Azure resources with OpenAI TS library openPipe works - for chat completions at least.

**Comment by arcticfly** [comment]
Thanks @Pbmangan. Closing this issue now.
