### ISSUE TITLE
Delete experiments from a project

### ISSUE THREAD

**Issue by s4nt0s** [OpenPipe/openpipe#195]
I'm just looking for a way to delete experiments within a project and the ability to delete the starting example project. I might just be missing the option, or maybe they haven't been added yet. I'm using the Openpipe website for now.

Great job on this project; it's very easy to use. I've played with a few different tools for evaluating models/prompts and this one is the best so far.

**Comment by arcticfly** [comment]
> Great job on this project; it's very easy to use. I've played with a few different tools for evaluating models/prompts and this one is the best so far.

Hey @s4nt0s, that's nice of you to say! Building open-source is a lot of fun.

> I'm just looking for a way to delete experiments within a project and the ability to delete the starting example project.

Yes, you can delete experiments within a project. The button for removing an experiment is nestled within the experiment settings drawer. I've included a couple screenshots that outline the deletion process.

Open the settings drawer:
<img width="1123" alt="settings-box" src="https://github.com/OpenPipe/OpenPipe/assets/41524992/6a7a85f9-f39f-4c0d-92aa-5841a1ed3844">

Delete the experiment:
<img width="1123" alt="delete-box" src="https://github.com/OpenPipe/OpenPipe/assets/41524992/0ee134d0-2d90-4a43-9d0d-c00fc6978560">


@corbt we should also add the ability to delete an experiment from the experiments list page to streamline this process in the future. I can take care of that.
