### ISSUE TITLE
Error: Missing required parameter: auth

### ISSUE THREAD

**Issue by kishansagathiya** [OpenPipe/openpipe#200]
Was trying to run OpenPipe locally and `pnpm prisma migrate dev` errored on `pnpm seed`.

Error is as follows
```
(node:420307) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/kishan/code/OpenPipe/node_modules/.pnpm/replicate@0.12.3/node_modules/replicate/index.js:37
      throw new Error('Missing required parameter: auth');
            ^


Error: Missing required parameter: auth
    at Replicate (/home/kishan/code/OpenPipe/node_modules/.pnpm/replicate@0.12.3/node_modules/replicate/index.js:37:13)
    at <anonymous> (/home/kishan/code/OpenPipe/app/src/modelProviders/replicate-llama2/getCompletion.ts:6:19)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.1
 ELIFECYCLE  Command failed with exit code 1.

An error occurred while running the seed command:
Error: Command failed with exit code 1: pnpm seed
```

Not sure if this has something to do with my machine (OS: ubuntu) or local setup, but opening this just in case.

<details closed>
<summary>Complete logs here</summary>
<br>
kishan@kishan-Inspiron-14-7425-2-in-1:~/code/OpenPipe/app$ pnpm prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "openpipe", schema "public" at "localhost:5432"

PostgreSQL database openpipe created at localhost:5432

Applying migration `20230701015916_init`
Applying migration `20230701042329_add_time_to_complete_to_model_output`
Applying migration `20230706193243_add_tokens_to_model_output`
Applying migration `20230706201223_add_evaluations`
Applying migration `20230714004556_add_construct_fn_to_prompt_variant`
Applying migration `20230714113205_create_scenariotvariant`
Applying migration `20230714182259_add_model_to_variant`
Applying migration `20230715004031_remove_default_value_for_model`
Applying migration `20230717203031_add_gpt4_eval`
Applying migration `20230718005301_add_gpt4_eval_type`
Applying migration `20230718201303_add_users_and_orgs`
Applying migration `20230719181731_remove_duplicate_scenario_variant_cell_fields`
Applying migration `20230719224611_add_cost_to_model_output`
Applying migration `20230720213215_add_model_providers`
Applying migration `20230725005817_use_id_as_streaming_channel`
Applying migration `20230725191512_migrate_model_response`
Applying migration `20230801195916_add_world_champs`
Applying migration `20230801234208_add_created_at_and_updated_at_to_users_table`
Applying migration `20230803163242_add_admin_role`
Applying migration `20230804042305_add_datasets`
Applying migration `20230805054033_migrate_construct_fn_to_prompt_constructor`
Applying migration `20230806024615_add_logged_calls_and_api_keys`
Applying migration `20230807044936_add_name_to_organization`
Applying migration `20230808034313_make_model_response_optional`
Applying migration `20230809222649_rename_organization_to_project`
Applying migration `20230810161437_add_uuid_extension`
Applying migration `20230811200114_rename_model_response_fields`
Applying migration `20230811231429_add_model_to_logged_call`
Applying migration `20230814233722_index_tags_by_project`
Applying migration `20230815234811_add_user_invitations`
Applying migration `20230818055303_add_slug_to_experiment`
Applying migration `20230822234224_add_fine_tunes`

The following migration(s) have been applied:

migrations/
  └─ 20230701015916_init/
    └─ migration.sql
  └─ 20230701042329_add_time_to_complete_to_model_output/
    └─ migration.sql
  └─ 20230706193243_add_tokens_to_model_output/
    └─ migration.sql
  └─ 20230706201223_add_evaluations/
    └─ migration.sql
  └─ 20230714004556_add_construct_fn_to_prompt_variant/
    └─ migration.sql
  └─ 20230714113205_create_scenariotvariant/
    └─ migration.sql
  └─ 20230714182259_add_model_to_variant/
    └─ migration.sql
  └─ 20230715004031_remove_default_value_for_model/
    └─ migration.sql
  └─ 20230717203031_add_gpt4_eval/
    └─ migration.sql
  └─ 20230718005301_add_gpt4_eval_type/
    └─ migration.sql
  └─ 20230718201303_add_users_and_orgs/
    └─ migration.sql
  └─ 20230719181731_remove_duplicate_scenario_variant_cell_fields/
    └─ migration.sql
  └─ 20230719224611_add_cost_to_model_output/
    └─ migration.sql
  └─ 20230720213215_add_model_providers/
    └─ migration.sql
  └─ 20230725005817_use_id_as_streaming_channel/
    └─ migration.sql
  └─ 20230725191512_migrate_model_response/
    └─ migration.sql
  └─ 20230801195916_add_world_champs/
    └─ migration.sql
  └─ 20230801234208_add_created_at_and_updated_at_to_users_table/
    └─ migration.sql
  └─ 20230803163242_add_admin_role/
    └─ migration.sql
  └─ 20230804042305_add_datasets/
    └─ migration.sql
  └─ 20230805054033_migrate_construct_fn_to_prompt_constructor/
    └─ migration.sql
  └─ 20230806024615_add_logged_calls_and_api_keys/
    └─ migration.sql
  └─ 20230807044936_add_name_to_organization/
    └─ migration.sql
  └─ 20230808034313_make_model_response_optional/
    └─ migration.sql
  └─ 20230809222649_rename_organization_to_project/
    └─ migration.sql
  └─ 20230810161437_add_uuid_extension/
    └─ migration.sql
  └─ 20230811200114_rename_model_response_fields/
    └─ migration.sql
  └─ 20230811231429_add_model_to_logged_call/
    └─ migration.sql
  └─ 20230814233722_index_tags_by_project/
    └─ migration.sql
  └─ 20230815234811_add_user_invitations/
    └─ migration.sql
  └─ 20230818055303_add_slug_to_experiment/
    └─ migration.sql
  └─ 20230822234224_add_fine_tunes/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.14.0 | library) to ./../node_modules/.pnpm/@prisma+client@4.14.0_prisma@4.14.0/node_modules/@prisma/client in 249ms

Running seed command `pnpm seed` ...

> openpipe-app@0.1.0 seed /home/kishan/code/OpenPipe/app
> tsx prisma/seed.ts

(node:420307) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/kishan/code/OpenPipe/node_modules/.pnpm/replicate@0.12.3/node_modules/replicate/index.js:37
      throw new Error('Missing required parameter: auth');
            ^

Error: Missing required parameter: auth
    at Replicate (/home/kishan/code/OpenPipe/node_modules/.pnpm/replicate@0.12.3/node_modules/replicate/index.js:37:13)
    at <anonymous> (/home/kishan/code/OpenPipe/app/src/modelProviders/replicate-llama2/getCompletion.ts:6:19)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.1
 ELIFECYCLE  Command failed with exit code 1.

An error occurred while running the seed command:
Error: Command failed with exit code 1: pnpm seed
kishan@kishan-Inspiron-14-7425-2-in-1:~/code/OpenPipe/app$ pnpm prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "openpipe", schema "public" at "localhost:5432"

Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (4.14.0 | library) to ./../node_modules/.pnpm/@prisma+client@4.14.0_prisma@4.14.0/node_modules/@prisma/client in 236ms

kishan@kishan-Inspiron-14-7425-2-in-1:~/code/OpenPipe/app$ 

</details>

**Comment by arcticfly** [comment]
Hey @kishansagathiya, thanks for reporting this. I think I know what's going on. At the moment, our user authentication system requires that a `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` be set in the `app/.env` file (see step 8 in https://github.com/OpenPipe/OpenPipe#running-locally). I know setting up the GitHub org can be a pain, and it's on our roadmap to make creating one optional.

Since we're currently spending most of our time building out the fine-tuning and deployment flow, a PR to simplify self-hosted user accounts would be much appreciated!
