### ISSUE TITLE
ImportError: cannot import name 'openai' from 'openpipe' (unknown location)

### ISSUE THREAD

**Issue by attili-sanjeet** [OpenPipe/openpipe#211]
Getting the above import error, once i have installed the openpipe via
```
pip install openpipe
```
Should we follow any more steps as well, [like this one](https://github.com/OpenPipe/OpenPipe#running-locally)
I'm trying to execute the jupyter notebooks available on the [examples](https://github.com/OpenPipe/OpenPipe/tree/main/examples/classify-recipes) folder, hope someone can help me setting this up.

**Comment by arcticfly** [comment]
Hey @attili-sanjeet, I just tried using openpipe in a Jupyter notebook and wasn’t able to reproduce your error. Have you gotten it resolved?

**Comment by attili-sanjeet** [comment]
Yes I have resolved it, internal instance issue
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by arcticfly** [comment]
Awesome, glad to hear it.
