### ISSUE TITLE
Sweep (fast): Official docker image / docker-compose?

### ISSUE THREAD

**Issue by sammcj** [OpenPipe/openpipe#224]
### Details

Features: It would be great if OpenPipe had an official Docker image, or at least a dockerfile so folks could build their own. Additional providing an example docker-compose.yaml to run the project containerised would lower the barrier to entry for a lot of folk.

**Comment by sammcj** [comment]
PR incoming for this, just trying to get past https://github.com/OpenPipe/OpenPipe/issues/225, once I have that working I'll submit a working PR with docker build, entrypoint script and example docker-compose.

**Comment by iguy0** [comment]
+1 =]

**Comment by stefanos-kalantzis** [comment]
any news on a docker image? it seems that #225 is closed

**Comment by davidsyoung** [comment]
+1 :)

**Comment by corbt** [comment]
Note: we’ve temporarily stopped development on the open-source version of the OpenPipe repository to integrate some proprietary third-party code. We hope to make the non-proprietary parts of the repository open again under an “open core” model once we get the bandwidth to do so. In the meantime, we are marking this repository as “archived” to let contributors know that it is no longer being maintained. Anyone is still free to fork and continue development off the existing open-source code, of course!
