### ISSUE TITLE
Sweep: Github oauth app - callback url? / constantly redirecting

### ISSUE THREAD

**Issue by sammcj** [OpenPipe/openpipe#225]
### Details

I just tried setting up OpenPipe as per the documentation, I created the Github oauth app but wasn't sure what to put in the callback URL - should this just be your local install base URL?

I suspect this is what is causing my instance to load -> redirect to github (and auth fine) -> redirect back to my app -> redirect back to github etc... over and over forever.

**Comment by corbt** [comment]
Yes, the callback URL should point to your local install: http://localhost:3000/api/auth/callback/github.

Would you mind updating the README to reflect that as well? Definitely an oversight on our part!

**Comment by DVGY** [comment]
@corbt May I make changes to README File for above ?

**Comment by sammcj** [comment]
Ah, great thanks! also - https://github.com/OpenPipe/OpenPipe/pull/228

**Comment by iguy0** [comment]
+1  =]
