### ISSUE TITLE
Codellama support?

### ISSUE THREAD

**Issue by rajivpoddar** [OpenPipe/openpipe#229]
Is codellama finetuning also supported?

**Comment by corbt** [comment]
Not currently, but it wouldn't be hard to add! Just out of my own curiousity, I'd be interested in knowing your use-case?

**Comment by rajivpoddar** [comment]
I am building an autonomous coding agent with GPT4. I have managed to get it to build simple Reactjs apps. I traced all my runs, built a dataset and fine-tuned GPT3.5. It worked! I'm wondering if I can do the same with codellama as well. The higher context length will be quite useful to build more complex apps.

**Comment by corbt** [comment]
Note: we’ve temporarily stopped development on the open-source version of the OpenPipe repository to integrate some proprietary third-party code. We hope to make the non-proprietary parts of the repository open again under an “open core” model once we get the bandwidth to do so. In the meantime, we are marking this repository as “archived” to let contributors know that it is no longer being maintained. Anyone is still free to fork and continue development off the existing open-source code, of course!
