### ISSUE TITLE
Seed is successful but the terminal process does not exits

### ISSUE THREAD

**Issue by DVGY07** [OpenPipe/openpipe#234]
<img width="756" alt="image" src="https://github.com/OpenPipe/OpenPipe/assets/144959919/ecdb2f9e-1c01-4a26-aede-39d9073c07ee">

The terminal is stuck here after seed is complete. Any one having these issues?

**Comment by corbt** [comment]
Unfortunately this is a known issue. You can just kill the hung process once seeding is complete. A PR to figure out why that's happening and get it to terminate correctly would be great!

**Comment by DVGY** [comment]
Well why that's happening is still is mystery because my other seed scripts run perfectly and exit automatically. I will try to look at it later why is it happening

Below code solves the issue
```js
seed().then(e=>{
 // .. do something
 process.exit(0) // This line of code helps exit it gracefully. and user can see seed complete message from prisma
 }).catch(e=>process.exit(1))

```

**Comment by corbt** [comment]
Hmm weird... not sure I'm super comfortable with this solution since I'd like to know what's actually keeping the process from shutting down normally to make sure we aren't eg. interrupting the background task that makes a bunch of API calls to OpenAI to fill out the sample experiments.

**Comment by DVGY** [comment]
It does not end because `generateNewCell(cell.promptVariantId, cell.testScenarioId, { stream: false })` Never ends, seems like it calls the `queryModelQueue` and it keeps it hanging.

**Comment by corbt** [comment]
I believe this is fixed.
