### ISSUE TITLE
feature request: Record embedding request

### ISSUE THREAD

**Issue by sheiy** [OpenPipe/openpipe#240]
<img width="403" alt="image" src="https://github.com/OpenPipe/OpenPipe/assets/12210038/668b55d4-ccf1-4ff0-aad7-db8ba8e1c7a5">

**Comment by corbt** [comment]
Interesting idea! I don't think we're a super great fit as a general-purpose observability platform just yet; is that the reason you're looking for this? Or is there some application you have in mind related to fine-tuning?

**Comment by sheiy** [comment]
@corbt `I don't think we're a super great fit as a general-purpose observability platform just yet; is that the reason you're looking for this? ` Yes 
`Or is there some application you have in mind related to fine-tuning?` No

**Comment by corbt** [comment]
Got it. I'll close this issue for now, but will revisit if we decide to go deeper on observability specifically!
