### ISSUE TITLE
Move LLM API call triggers from UI to server

### ISSUE THREAD

**Issue by arcticfly** [OpenPipe/openpipe#33]
We currently trigger calls to LLM API's in `OutputCell` in the UI. We should move these triggers to the server so that we don't have to render every cell in order to run our experiment against all scenarios and prompt variants.

Blocks: https://github.com/OpenPipe/OpenPipe/issues/34

## Architectural Changes:

At a high level, we need to do the following:
* Add Bull jobs to make requests to LLMs and retry if they fail
* Create a streaming channel id on the server instead of the frontend as we currently do so that requests can start with streaming enabled, even if the user is not currently viewing the model output in question
* Poll the server from in `OutputCell` on the frontend

#### Existing flow
1. New scenario or variant on the experiment generates new scenario-variant combination
2. Website invalidates experiment data in cache and requests updated data, which includes new cells
3. Website renders `OutputCell`s for each scenario-variant combination
4. Each `OutputCell` makes a request to the server for its corresponding `ModelOutput` in the database. We return here if either of the conditions are met:
   1. If the scenario-variant key exists in the database, it's immediately returned
   2. If the `inputHash` of the scenario-variant exists in the database (meaning that another scenario-variant has an identical templatized prompt), a new `ModelOutput` for this scenario-variant is generated with the same output as the existing `ModelOutput`'s output values
5. Otherwise, we call `getChatCompletion` and pass the `channel` if the frontend supplied one for streaming purposes
6. We forward the templated prompt to the correct LLM, and stream completions to the websocket server if they come in. In the event of rate limiting, the server returns a rate limit error, and the frontend repeats step 4 up to 3 times
7. When the model output is generated, we create a new `ModelOutput` and return it. The website invalidates prompt stats, so that cost and evaluation metrics can be updated

Our new process will generate output and update prompt stats without relying on all `OutputCell`s being rendered.

#### New flow
1. New scenario or variant on the experiment results in new scenario-variant combination
2. For each new scenario-variant combination, one of the following occurs:
    1. If the scenario-variant's `inputHash` exists in the database, we generate a new `ModelOutput` with identical output values to the existing `ModelOutput`
    2. If the `inputHash` does not exist, we create a new `ModelOutput` row in our database marked as `PENDING` with empty output values and queue a Bull job to handle requests to the LLM.
3. The website invalidates its cached experiment data and receives the updated variants and scenarios. If any `ModelOutput`s are `PENDING` or `IN_PROGRESS`, the website starts polling for updated prompt stats once a second until all `ModelOutput`s are marked as `COMPLETE` or `ERROR`.
4. Requests for variant-scenario data are made in individual `OutputCell`s, and are handled depending on status:
    1. `COMPLETE` - Processed much the same, and data is rendered in the OutputCell
    2. `PENDING` - Cause the output cell to poll once a second for updates and display a waiting indicator
    3. `IN_PROGRESS` - Potentially includes a `streamingChannel`, which causes the `OutputCell` to open a socket to receive streaming updates for the response, which are rendered as they are received. If a `ModelOutput` is rate-limited and waiting to try its next request, a countdown is displayed
    4. `ERROR` - `Error is displayed, along with a retry button
5. Meanwhile, the Bull jobs on the server are working to update `ModelOutput`s in the following steps:
    1. When the job begins, it first checks to see if the `ModelOutput`'s status is still `PENDING` or `ERROR`.
        1. If it is neither of these two, the job immediately finishes. This ensures that we don't have two jobs working on the same `ModelOutput` in parallel.
        2. If it is pending, it updates the status to be `IN_PROGRESS`
     2. The job calls `getChatCompletion` with the prompt and `streamingChannel`.
       1. If the request succeeds, we update the `outputStatus` to `COMPLETE` and end the job
       2. If the request fails due to rate limiting and we our under our limits of automatic requests, we calculate the next time we should try the request using exponential backoff and save it as `retryTime` in the database for the website to poll. After the allotted time we repeat step 2.
       3. If the request fails under other circumstances, we generate an `errorMessage`, save it in the database, and end the job
6. When all `ModelOutput`s are marked as `COMPLETE` or `ERROR`, we stop polling on the frontend

### Changes to `ModelOutput` in database
We'll need to add a couple new fields to the `ModelOutput` rows we store in the database. Fields that are generated when the completion is received, such as `timeToComplete` and `statusCode`, need to be optional.

Original schema: https://github.com/OpenPipe/OpenPipe/blob/main/prisma/schema.prisma#L78

New schema:
```
enum OutputStatus { // New
  PENDING
  IN_PROGRESS
  COMPLETE
  ERROR
}

model ModelOutput {
    id String @id @default(uuid()) @db.Uuid

    model            String // New
    inputHash        String
    outputStatus     OutputStatus @default(COMPLETE) // New
    output           Json? // Make optional
    statusCode       Int? // Make optional
    errorMessage     String?
    timeToComplete   Int?     @default(0) // Make optional
    retryTime        DateTime? // New
    streamingChannel String? // New

    promptTokens     Int?
    ...
```

**Comment by corbt** [comment]
This is a very necessary change. A few thoughts on implementation specifics:

1. I've used Graphile Worker (https://github.com/graphile/worker) in the past and been quite happy with it, compared to Bull. It doesn't have the same amount of infra around it that Bull has (notably, it doesn't have an admin UI) but it would allow us to keep only a dependency on Postgres, instead of having to add a Redis server as well. That'll make running locally and deployments easier for users.
2. When I start seeing a lot of optional fields on a model that are either all set or all blank, that raises my spidey sense that it might actually be better off as two models that reference each other. I wonder if instead of making some of the completion fields optional might it be better to add a new model `IncompleteModelOutput` that contains the `outputStatus`, `streamingChannel` and references `modelOutputId` instead of making all the other fields optional? Just a thought.
3. The queuing library (either Graphile Worker or Bull) should allow us to schedule jobs for a specific time; I don't think we need to include `retryTime` in our application code.

**Comment by arcticfly** [comment]
I’ll take a look at Graphile, thanks for the suggestion!

Let me think about creating a new model, that’s an interesting idea.

I think we do need to save `retryTime` in the database so that we can display a countdown in the UI.

**Comment by arcticfly** [comment]
**UPDATED PLAN:**

## Architectural Changes:

At a high level, we need to do the following:
* Add Graphile jobs to make requests to LLMs and retry if they fail
* Create a streaming channel id on the server instead of the frontend as we currently do so that requests can start with streaming enabled, even if the user is not currently viewing the model output in question
* Poll the server from in `OutputCell` on the frontend

### Changes to model completion trigger flow

#### Existing flow
1. New scenario or variant on the experiment generates new scenario-variant combination
2. Website invalidates experiment data in cache and requests updated data, which includes new cells
3. Website renders `OutputCell`s for each scenario-variant combination
4. Each `OutputCell` makes a request to the server for its corresponding `ModelOutput` in the database. We return here if either of the conditions are met:
   1. If the scenario-variant key exists in the database, it's immediately returned
   2. If the `inputHash` of the scenario-variant exists in the database (meaning that another scenario-variant has an identical templatized prompt), a new `ModelOutput` for this scenario-variant is generated with the same output as the existing `ModelOutput`'s output values
5. Otherwise, we call `getChatCompletion` and pass the `channel` if the frontend supplied one for streaming purposes
6. We forward the templated prompt to the correct LLM, and stream completions to the websocket server if they come in. In the event of rate limiting, the server returns a rate limit error, and the frontend repeats step 4 up to 3 times
7. When the model output is generated, we create a new `ModelOutput` and return it. The website invalidates prompt stats, so that cost and evaluation metrics can be updated

Our new process will generate output and update prompt stats without relying on all `OutputCell`s being rendered.

#### New flow
1. New scenario or variant on the experiment results in new scenario-variant combination
2. For each new scenario-variant combination, one of the following occurs:
    1. If the scenario-variant's `inputHash` exists in the database, we generate a new `ScenarioVariant` and `ModelOutput` with identical output values to the existing records
    2. If the `inputHash` does not exist, we create a new `ScenarioVariant` row in our database and queue a Graphile job to handle requests to the LLM.
3. The website invalidates its cached experiment data and receives the updated variants and scenarios. If any `ScenarioVariant`s are in progress , the website starts polling for updated prompt stats once a second until they are all complete
4. Requests for variant-scenario data are made in individual `OutputCell`s, and are handled depending on status:
    1. Complete - Processed much the same as now, data is rendered in the OutputCell, polling stops
    2. Error - Error is displayed along with a retry button, polling stops
    3. In progress - Potentially includes a `streamingChannel`, which causes the `OutputCell` to open a socket to receive streaming updates for the response, which are rendered as they are received. If a `ScenarioVariant` is rate-limited and waiting to try its next request, a countdown is displayed. Otherwise a waiting indicator is rendered. The cell starts polling once a second.
6. Meanwhile, the Graphile jobs on the server follow these steps:
    1. When the job begins, it first checks to see if a `ModelOutput` for the `ScenarioVariant` already exists. If so, the job immediately finishes.
    2. The job checks to see if the response should be streamed, and if so saves a `streamingChannel` on the `ScenarioVariant`
    3. The job calls `getChatCompletion` with the prompt and `streamingChannel`
       1. If the request succeeds, we update save a new `ModelOutput` for the `ScenarioVariant` and end the job
       2. If the request fails due to rate limiting and we are under our limit for automatic requests, we calculate the next time we should try the request using exponential backoff and save it as `retryTime` in the database for the website to poll. After the allotted time we repeat step 2.
       3. If the request fails under other circumstances, we save `errorMessage` on the `ScenarioVariant`
7. When all `ScenarioVariants`s have model output or an error, we stop polling experiment stats on the frontend

### Database changes
Our existing `ModelOutput` schema will be renamed to `ScenarioVariant`, and a new `ModelOutput` table with only the values that are generated after a response from an LLM is received will be stored within it.

Existing schema (https://github.com/OpenPipe/OpenPipe/blob/main/prisma/schema.prisma#L78):
```
model ModelOutput {
    id String @id @default(uuid()) @db.Uuid

    inputHash      String
    output         Json
    statusCode     Int
    errorMessage   String?
    timeToComplete Int     @default(0)

    promptTokens     Int? // Added promptTokens field
    completionTokens Int? // Added completionTokens field

    promptVariantId String        @db.Uuid
    promptVariant   PromptVariant @relation(fields: [promptVariantId], references: [id], onDelete: Cascade)

    testScenarioId String       @db.Uuid
    testScenario   TestScenario @relation(fields: [testScenarioId], references: [id], onDelete: Cascade)

    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt

    @@unique([promptVariantId, testScenarioId])
    @@index([inputHash])
}
```


New schema:
```
model ScenarioVariant {
    id String @id @default(uuid()) @db.Uuid

    model            String
    inputHash        String
    statusCode       Int?
    errorMessage     String?
    retryTime        DateTime?
    streamingChannel String?

    promptVariantId String        @db.Uuid
    promptVariant   PromptVariant @relation(fields: [promptVariantId], references: [id], onDelete: Cascade)

    testScenarioId String       @db.Uuid
    testScenario   TestScenario @relation(fields: [testScenarioId], references: [id], onDelete: Cascade)

    modelOutput   ModelOutput?

    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt

    @@unique([promptVariantId, testScenarioId])
    @@index([inputHash])
}

model ModelOutput {
    id String @id @default(uuid()) @db.Uuid

    output           Json
    timeToComplete   Int     @default(0)
    promptTokens     Int?
    completionTokens Int?

    scenarioVariantId String        @db.Uuid
    scenarioVariant   ScenarioVariant @relation(fields: [scenarioVariantId], references: [id])
}
```
