### ISSUE TITLE
support openai lib: 4.15.3 

### ISSUE THREAD

**Issue by caoer** [OpenPipe/openpipe#335]
the code here only works for `4.8.0`: https://github.com/OpenPipe/OpenPipe/blob/main/client-libs/typescript/src/openai/streaming.ts#L13

in the latest version, current(`4.15.3`): it is here: https://github.com/openai/openai-node/blob/e0138e8a5939f6fe53639df78cd541e4e20927ed/src/streaming.ts#L21C24-L21C24

related PR: https://github.com/openai/openai-node/pull/370
The problem is that current OpenPipe's OpenAI lib does not work for `streaming` API due to refactoring of the PR above. 

can we update to support latest code?

@arcticfly @corbt

**Comment by corbt** [comment]
Yep this makes sense. Feel free to open a PR, if not we'll definitely get to this as soon as we can!

**Comment by arcticfly** [comment]
Reopening to fix the streaming bug in particular.

**Comment by arcticfly** [comment]
@caoer Thanks for pointing this out. Should be fixed in https://github.com/OpenPipe/OpenPipe/pull/340.

Could you try out version `0.6.2` and see if you get the same error?

**Comment by caoer** [comment]
Thanks @arcticfly and @corbt !
 I've tested, it is working OK now. 

```
    "openai": "4.17.3",
    "openpipe": "0.6.2",
```
