### ISSUE TITLE
Unable  to find the train.jsonl and test.jsonl from the classifying recipes example

### ISSUE THREAD

**Issue by PsyCharan17** [OpenPipe/openpipe#373]
I was trying to follow through the sample example of classifying recipes but was unable to find the train.jsonl and test.jsonl in the repository which was supposed to be in the ./data/ folder. 
I would request the team to include the dataset  as It would help out all future contributors like me who can't incur the costs of classifying using gpt4 to try out openpipe.

Thanks & Regards.
![image](https://github.com/OpenPipe/OpenPipe/assets/88344386/f8c13c79-b356-4725-b591-2caaaad7199a)

**Comment by arcticfly** [comment]
Hey @PsyCharan17, you have to generate those files yourself. I've updated the tutorial to clarify the process: https://github.com/OpenPipe/OpenPipe/commit/ce132ea32d8aa2148fe9be3a9b6f07741d056276

**Comment by Nuclear6** [comment]
I have the same question: why can't we just download the train.jsonl file directly? This would save beginners some costs and also lower the barrier to entry.
