### ISSUE TITLE
Error 404 when reaching app - Lost saved experiments

### ISSUE THREAD

**Issue by droussis** [OpenPipe/openpipe#445]
Hello,
I cannot open saved experiments which were accessible through [this link](https://app.openpipe.ai/experiments), as I get a 404 error.
In that way, I lost various experiments I had worked on, and thus a lot of prompt engineering work. 
Is this issue temporary? Is there a way to retrieve the latest logs of my experiments?
Thank you very much!

**Comment by arcticfly** [comment]
Hey @droussis, thanks for using the experiments platform. We deprecated prompt experiments in October and finally removed the code for hosting them a couple weeks ago to focus on fine-tuning.

If you’d like us to send you the prompt variants you were using in our latest database snapshot, email founders@openpipe.ai. Thanks again, and sorry for the inconvenience.
