### ISSUE TITLE
CORS cross origin errors when running locally - Same Origin Policy

### ISSUE THREAD

**Issue by justfinethanks** [OpenPipe/openpipe#449]
Occurring after click upload in the dataset upload to Azure - causing issue. Running locally with no config changes.

**Comment by justfinethanks** [comment]
![Screenshot 2023-12-21 at 2 09 17 PM](https://github.com/OpenPipe/OpenPipe/assets/1246016/ac84cbe7-8ec2-44a3-9c47-8e9498265c2b)

**Comment by corbt** [comment]
I believe this is fixed, let us know if it's still an issue for you.
