### ISSUE TITLE
Tags not showing up on the ui

### ISSUE THREAD

**Issue by codebanesr** [OpenPipe/openpipe#457]
Hi guys, first off, thanks a lot for the awesome project

I noticed that the tags and chain_name columns seem to be the same. Is that correct?. If yes, then maybe the documentation is outdated!. Also, should the chain_name column appear by default? I was having trouble finding the tags column. Thanks!

**Comment by corbt** [comment]
Hey @codebanesr thanks for the report! Can you post a screenshot of the issue? I'm afraid I don't fully follow.

**Comment by codebanesr** [comment]
sure, this is how we initialize openpipe in the codebase, note: `chain_name=tag`
```
def get_chat_model(tag: str = "no_tag") -> BaseChatModel:
    if model_name == CHAT_MODELS.gpt_3_5_turbo:
        model = ChatOpenAI(
            model=CHAT_MODELS.gpt_3_5_turbo,
            temperature=0,
            openpipe_kwargs={
                "api_key": llm_consts.openpipe_api_key,
            },
        ).with_tags(chain_name=tag, caller="shanur")
        
        ...
 ```
 
 Screenshot from dashboard, says `chain_name`
<img width="1221" alt="Screenshot 2024-01-08 at 2 30 11 AM" src="https://github.com/OpenPipe/OpenPipe/assets/17947802/dec56db2-11b1-48f8-8518-e8b60cfafa25">

- And the screenshot from pypi.org, calls it tags
<img width="949" alt="Screenshot 2024-01-08 at 2 31 27 AM" src="https://github.com/OpenPipe/OpenPipe/assets/17947802/c2850726-9e7b-4253-9d84-c1f589308454">

**Comment by corbt** [comment]
Ah, I think I see. Unfortunately, we haven't built an explicit integration with the Langchain tagging functionality. I recommend you use [our SDK](https://docs.openpipe.ai/getting-started/openpipe-sdk) directly if you're planning on using tagging!
