### ISSUE TITLE
Feature Request: Adding new rows to dataset

### ISSUE THREAD

**Issue by anunayajoshi** [OpenPipe/openpipe#481]
Has been quite pleasant to use openpipe. My biggest problem I'm facing right now, is that the only way for me to add a new row into my dataset, is to have it from my request logs, add it to my dataset, and then edit that row. 

I can update rows in the dataset, but I would like to be able to add rows into the dataset table as well.

I believe it'll be a pretty easy feature to add, since the updating UI is already built via the dataset table.

**Comment by arcticfly** [comment]
Hey @anunayajoshi, how would you like to be able to add new rows? You can currently import them from the request logs, or upload a .jsonl file in the dataset's General tab.

**Comment by corbt** [comment]
Closing until we have a bit more clarity on the ask here.
