### ISSUE TITLE
Unclear how scenario variables can be used in evals

### ISSUE THREAD

**Issue by jamesmurdza** [OpenPipe/openpipe#52]
Re-reading the instructions, I now see how to do this, but maybe this can be made clearer.

<img width="502" alt="Screenshot 2023-07-17 at 2 43 14 PM" src="https://github.com/OpenPipe/OpenPipe/assets/33395784/9c8c127f-5807-4e9a-9eda-df24ba61bb50">

**Comment by corbt** [comment]
Thanks so much! I've updated the wording there a little so hopefully it'll be more clear.

We're also going to need to do a larger overhaul of evaluations at some point to improve the UX, but hopefully they're in a good enough place to be useful already!
