### ISSUE TITLE
Fine-tuned Model sizes are double the base model size.

### ISSUE THREAD

**Issue by adriancowham** [OpenPipe/openpipe#591]
I fine-tuned the Mistral 7B model and downloaded the weights. The downloaded weights were about 30GB. The original OpenPipe Mistral 7B weights are about 15GB with Tensor Type `BF16`. I noticed after downloading the fine-tuned weights the Tensor Type was `FP32`. This isn't too much of an issue with the smaller models, it's easy enough to download them and then `half()` them. However, the Mixtral model at `FP32` is 180GB, and is taking a longer to download.

In an email exchange with Kyle, he seemed to think that since the merging code did not specify the `torch_dtype` that the `transformers` library was using `FP32` as the default. 

Would it be possible to set `torch_dtype` to the base model's Tensor Type? This would make exporting weights faster, downloading weights faster and hopefully eliminate or reduce OOM on your side. Also, apologies for being prescriptive. This may or not be the root cause and there might be a better solution.

Thank you.

**Comment by arcticfly** [comment]
Hey Adrian! Specifying the weight format in which a model can be exported is on our roadmap, but we may not get to it for a few weeks. Does that timeline work for you, or do you need this feature sooner than that?

**Comment by arcticfly** [comment]
@adriancowham Should work now! We added `bf16` and `fp16` as additional export formats.
