### ISSUE TITLE
Strict version constraint `openai = "~1.7.0"` in Python client prevents updating packages

### ISSUE THREAD

**Issue by ErikBjare** [OpenPipe/openpipe#609]
I've been trying out OpenPipe (love the idea!), but today I got into a situation where I needed to update the `openai` package (installing `langchain-openai` requires me to do so).

I can see how it might be a lot of work for you to keep up-to-date with the latest `openai` version, but since my need for using the latest `openai` package is greater than my need to try out OpenPipe, I might have to drop OpenPipe. 

Before I do so, I wanted to reach out and check what the status is on that version constraint, and if it can be updated/relaxed.

**Comment by arcticfly** [comment]
@ErikBjare thanks for opening the issue! We just released version `4.4.1`, which supports openai versions `>=1.7,<=1.12`.

Would you mind confirming that you're able to install the updated version?

**Comment by ErikBjare** [comment]
Works like a charm, thanks! ❤️
