### ISSUE TITLE
Can't export requests

### ISSUE THREAD

**Issue by Van0SS** [OpenPipe/openpipe#675]
Browser's console shows Content Security Policy issue when trying to export requests on app.openpipe.ai

Firefox:
<img width="1211" alt="image" src="https://github.com/OpenPipe/OpenPipe/assets/8650658/29e84a7d-10b6-4bf2-a815-d049b08c3ed9">

Chrome:
<img width="625" alt="image" src="https://github.com/OpenPipe/OpenPipe/assets/8650658/c2cd1566-8a2b-4dca-af19-408911e1cb68">

**Comment by corbt** [comment]
Thanks we'll take a look!
