### ISSUE TITLE
Bug: Openpipe dashboard crashes when viewing fine tune evaluations

### ISSUE THREAD

**Issue by samcfinan** [OpenPipe/openpipe#691]
Navigating to a newly trained model's test set performance by hitting View Evaluation results in the following error on the OpenPipe dashboard:

Application error: a client-side exception has occurred (see the browser console for more information).

Looks to be a NextJS error.

Blocking us from seeing model performance.

More details: using Chrome Version 122.0.6261.112 (Official Build) (arm64) on MacOS 14.2

**Comment by corbt** [comment]
Thanks. We've verified that there's a client-side error that occurs sometimes on this page -- will figure out a fix and let you know!

**Comment by corbt** [comment]
Fixed in https://github.com/OpenPipe/OpenPipe/pull/693!
