### ISSUE TITLE
openpipe and httpx

### ISSUE THREAD

**Issue by db-aeon** [OpenPipe/openpipe#700]
I can't get around this pip error:

`openpipe 4.7.0 requires httpx<0.25.0,>=0.24.1, but you have httpx 0.27.0 which is incompatible.`

httpx 0.24.1 was released May of last year, and downgrading to it causes a bunch of other incompatibilities with other libraries.  Any way to loosen this restriction?

**Comment by aidanmclaughlin** [comment]
+1 Here.

I literally cannot use openpipe because of its strict httpx requirements. I've dug through what's public here and it seems very unlikley openpipe can't use newer httpx.

Excited for this product but I'll have to wait until this is resolved!

**Comment by ashishb** [comment]
I built https://observeapi.com/ that proxies log to OpenPipe

1. The logs are sent to OpenPipe asynchronously, so, no downtime is lost when OpenPipe is down.
2. No version-compatibility issues like the once you mentioned

**Comment by arcticfly** [comment]
@db-aeon @aidanmclaughlin @ashishb Sorry all, this issue was resolved in an update to our python sdk a few months ago, and we forgot to update you! To get our attention faster next time, feel free to shoot an email to support@openpipe.ai. Let us know what else we can improve!
